name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@v1.0.2 #Github Action version
        with:
          project_name: ${{ github.repository }}
          cx_tenant: nfr_guidepoint_nfr
          base_uri: https://ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with: 
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif
